# Generated by Django 5.0 on 2024-05-21 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_template', '0001_initial'),
        ('hackathon', '0002_rename_team_size_hackathons_team_size_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathons'),
        ),
    ]
