# Generated by Django 5.0 on 2024-05-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_rename_team_size_hackathons_team_size_min_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='hackathon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathons'),
        ),
        migrations.AlterField(
            model_name='teamrequestedmembers',
            name='hackathon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathons'),
        ),
    ]
