# Generated by Django 5.0 on 2024-05-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_anonymoususer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
    ]
