# Generated by Django 5.0 on 2024-05-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0003_textproperties_line_height'),
        ('team', '0002_teamrequestedmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrequestedmembers',
            name='hackathon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon'),
        ),
    ]
