# Generated by Django 4.2.6 on 2023-10-31 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(max_length=250, upload_to='logo')),
                ('name', models.CharField(max_length=250)),
                ('mode_of_conduct', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=250)),
                ('deadline', models.DateField()),
                ('team_size', models.IntegerField()),
                ('visible', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('start_date_time', models.DateTimeField()),
                ('about', models.TextField()),
                ('image1', models.ImageField(max_length=250, upload_to='image')),
                ('image2', models.ImageField(max_length=250, upload_to='image')),
                ('image3', models.ImageField(max_length=250, upload_to='image')),
                ('image4', models.ImageField(max_length=250, upload_to='image')),
                ('image5', models.ImageField(max_length=250, upload_to='image')),
                ('website', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('start_timeline', models.DateTimeField()),
                ('end_timeline', models.DateTimeField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_host.hackathon')),
            ],
        ),
    ]
