# Generated by Django 4.2.6 on 2023-11-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_host', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='brief',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='contact1_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='contact1_numner',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='contact2_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='contact2_numner',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='venue',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
