# Generated by Django 4.2.6 on 2023-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_host', '0003_hackathon_brief_hackathon_contact1_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='contact1_numner',
            new_name='contact1_number',
        ),
        migrations.RenameField(
            model_name='hackathon',
            old_name='contact2_numner',
            new_name='contact2_number',
        ),
    ]
