# Generated by Django 5.0 on 2024-05-21 10:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0002_rename_team_size_hackathons_team_size_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTemplate',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathons')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_template', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='custom_template.customtemplate')),
            ],
        ),
    ]
