# Generated by Django 5.0 on 2024-05-19 16:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathons',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.CharField(blank=True, default='', max_length=2000)),
                ('name', models.CharField(max_length=250)),
                ('organisation_name', models.CharField(default=None, max_length=250)),
                ('brief', models.TextField(default=None)),
                ('deadline', models.DateField()),
                ('start_date_time', models.DateTimeField()),
                ('team_size', models.IntegerField()),
                ('fee', models.CharField(blank=True, default=None, max_length=100)),
                ('total_number_rounds', models.IntegerField(blank=True, null=True)),
                ('form_exist', models.BooleanField(default=False)),
                ('number_of_registeration', models.IntegerField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathon_user', to='user.userprofile')),
            ],
        ),
    ]
