# Generated by Django 5.0 on 2024-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathons',
            old_name='team_size',
            new_name='team_size_min',
        ),
        migrations.AddField(
            model_name='hackathons',
            name='team_size_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
