# Generated by Django 5.0 on 2024-05-19 22:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonRegisterationForm',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('number_of_fields', models.IntegerField(null=True)),
                ('hackathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon.hackathons')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('error_text', models.CharField(max_length=500)),
                ('hint', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=500)),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='DropdownField',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('error_text', models.CharField(max_length=500, null=True)),
                ('label', models.CharField(max_length=200, null=True)),
                ('required', models.BooleanField(default=False)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('label', models.CharField(max_length=100, null=True)),
                ('error_text', models.CharField(max_length=500)),
                ('min_date', models.DateField()),
                ('max_date', models.DateField()),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='LongAnswerField',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('word_limit', models.IntegerField()),
                ('label', models.CharField(max_length=1000)),
                ('error_text', models.CharField(max_length=500)),
                ('required', models.BooleanField()),
                ('hint', models.CharField(max_length=1000, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceField',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('error_text', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200, null=True)),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='OptionDropdown',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500)),
                ('serial_number', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.dropdownfield')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('related', models.CharField(choices=[('RADIO', 'Radio'), ('CHECK', 'Checkbox')], max_length=500, null=True)),
                ('text', models.CharField(max_length=500)),
                ('serial_number', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.multiplechoicefield')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('section_name', models.CharField(max_length=500)),
                ('number_of_questions', models.IntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswerField',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('validation', models.CharField(max_length=200)),
                ('hint', models.CharField(max_length=1000)),
                ('label', models.CharField(max_length=500)),
                ('error_text', models.CharField(max_length=500)),
                ('required', models.BooleanField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('error_text', models.CharField(max_length=500)),
                ('labels', models.JSONField(default={})),
                ('label', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=10, null=True)),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='Stepper',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=500, null=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('error_text', models.CharField(max_length=500)),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('error_text', models.CharField(max_length=500)),
                ('label', models.CharField(max_length=500)),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
        migrations.CreateModel(
            name='TagOptions',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500)),
                ('serial_number', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Toggle',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField(null=True)),
                ('label', models.CharField(max_length=500)),
                ('error_text', models.CharField(max_length=500)),
                ('required', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
            ],
        ),
    ]
