# Generated by Django 5.0 on 2024-02-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfield',
            name='type',
        ),
    ]
