# Generated by Django 5.0 on 2024-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='label',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='min_value',
        ),
        migrations.AddField(
            model_name='slider',
            name='labels',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='date',
            name='max_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='date',
            name='min_date',
            field=models.DateField(),
        ),
    ]
