# Generated by Django 5.0 on 2024-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longanswerfield',
            name='hint',
            field=models.CharField(max_length=1000),
        ),
    ]
