# Generated by Django 5.0 on 2024-05-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0001_initial'),
        ('user_participation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fileupload',
            new_name='File',
        ),
    ]
