# Generated by Django 5.0 on 2024-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0002_remove_slider_label_remove_slider_max_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdownfield',
            name='choices',
            field=models.CharField(max_length=20),
        ),
    ]
