# Generated by Django 5.0 on 2024-04-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0003_alter_dropdownfield_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicefield',
            name='label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
