# Generated by Django 5.0 on 2024-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0004_multiplechoicefield_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepper',
            name='label',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
