# Generated by Django 5.0 on 2024-04-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0005_stepper_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
