# Generated by Django 5.0 on 2024-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0006_date_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
