# Generated by Django 5.0 on 2024-05-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0007_slider_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='multiplechoicefield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slider',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stepper',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tags',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toggle',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
