# Generated by Django 5.0 on 2024-05-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0008_date_required_fileupload_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='hint',
        ),
    ]
