# Generated by Django 5.0 on 2024-05-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0009_remove_slider_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='related',
            field=models.CharField(choices=[('RADIO', 'Radio'), ('CHECK', 'Checkbox')], max_length=500, null=True),
        ),
    ]
