# Generated by Django 5.0 on 2024-05-09 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0011_tagoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionDropdown',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('related', models.CharField(choices=[('RADIO', 'Radio'), ('CHECK', 'Checkbox')], max_length=500, null=True)),
                ('text', models.CharField(max_length=500)),
                ('serial_number', models.IntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.dropdownfield')),
            ],
        ),
    ]
