# Generated by Django 5.0 on 2024-05-09 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0012_optiondropdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiondropdown',
            name='related',
        ),
    ]
