# Generated by Django 5.0 on 2024-05-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0013_remove_optiondropdown_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownfield',
            name='choices',
        ),
    ]
