# Generated by Django 5.0 on 2024-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0014_remove_dropdownfield_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownfield',
            name='error_text',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dropdownfield',
            name='label',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dropdownfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
