# Generated by Django 5.0 on 2024-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0015_dropdownfield_error_text_dropdownfield_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='longanswerfield',
            name='hint',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
