# Generated by Django 5.0 on 2024-05-15 17:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('text', 'text'), ('container', 'container')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeHackathon',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Containerproperty',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Color', models.CharField(blank=True, max_length=200, null=True)),
                ('border_color', models.CharField(blank=True, max_length=200, null=True)),
                ('border_radius', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('box_shadow_color', models.CharField(blank=True, max_length=200, null=True)),
                ('blur_radius', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('focused_border_color', models.CharField(blank=True, max_length=200, null=True)),
                ('border_width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('container', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.container')),
            ],
        ),
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.CharField(blank=True, default='', max_length=2000)),
                ('name', models.CharField(max_length=250)),
                ('organisation_name', models.CharField(default=None, max_length=250)),
                ('mode_of_conduct', models.CharField(max_length=250)),
                ('deadline', models.DateField()),
                ('team_size', models.IntegerField()),
                ('visible', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10)),
                ('start_date_time', models.DateTimeField()),
                ('about', models.TextField()),
                ('brief', models.TextField(default=None)),
                ('image1', models.CharField(blank=True, max_length=250)),
                ('image2', models.CharField(blank=True, max_length=250)),
                ('image3', models.CharField(blank=True, max_length=250)),
                ('image4', models.CharField(blank=True, max_length=250)),
                ('image5', models.CharField(blank=True, max_length=250)),
                ('fee', models.CharField(blank=True, default=None, max_length=100)),
                ('venue', models.CharField(default=None, max_length=500)),
                ('contact1_name', models.CharField(blank=True, default=None, max_length=250)),
                ('contact2_number', models.CharField(default=None, max_length=10)),
                ('form_exist', models.BooleanField(default=False)),
                ('number_of_registeration', models.IntegerField(blank=True, default=None, null=True)),
                ('contact1_number', models.CharField(default=None, max_length=10)),
                ('contact2_name', models.CharField(blank=True, default=None, max_length=250)),
                ('discord', models.CharField(blank=True, default=None, max_length=200)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('website', models.CharField(blank=True, default=None, max_length=100)),
                ('github', models.CharField(blank=True, default='', max_length=200)),
                ('facebook', models.CharField(blank=True, default='', max_length=200)),
                ('twitter', models.CharField(blank=True, default='', max_length=200)),
                ('linkedin', models.CharField(blank=True, default='', max_length=200)),
                ('total_number_rounds', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('text', 'text'), ('container', 'container')], max_length=200, null=True)),
                ('hackathon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon'),
        ),
        migrations.CreateModel(
            name='HackathonViews',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view', models.PositiveIntegerField()),
                ('hackathon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('start_timeline', models.DateTimeField()),
                ('end_timeline', models.DateTimeField()),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon')),
            ],
        ),
        migrations.CreateModel(
            name='Textproperties',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('font', models.CharField(blank=True, max_length=200, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('text_color', models.CharField(blank=True, max_length=200, null=True)),
                ('font_weight', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=100, message='Value must be greater than or equal to {limit_value}.'), django.core.validators.MaxValueValidator(limit_value=900, message='Value must be less than or equal to {limit_value}.')])),
                ('italics', models.BooleanField(blank=True, null=True)),
                ('underline', models.BooleanField(blank=True, null=True)),
                ('strikethrogh', models.BooleanField(blank=True, null=True)),
                ('upper_case', models.BooleanField(blank=True, null=True)),
                ('align', models.CharField(choices=[('right', 'right'), ('left', 'left'), ('center', 'center'), ('justify', 'justify')], max_length=10)),
                ('letter_spacing', models.IntegerField(blank=True, null=True)),
                ('field', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.field')),
            ],
        ),
    ]
