# Generated by Django 5.0 on 2024-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerproperty',
            name='blur_radius',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='containerproperty',
            name='border_radius',
            field=models.FloatField(blank=True),
        ),
    ]
