# Generated by Django 5.0 on 2024-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='total_number_rounds',
            field=models.IntegerField(null=True),
        ),
    ]
