# Generated by Django 5.0 on 2024-05-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='start_date_time',
        ),
    ]
