# Generated by Django 5.0 on 2023-12-18 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon'),
        ),
    ]
