# Generated by Django 5.0 on 2024-02-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='form_exist',
            field=models.BooleanField(default=False),
        ),
    ]
