# Generated by Django 5.0 on 2024-02-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0002_hackathon_form_exist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='image1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
