# Generated by Django 5.0 on 2024-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0002_alter_hackathon_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='logo',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
