# Generated by Django 5.0 on 2023-12-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0002_field_hackathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='style',
        ),
        migrations.AddField(
            model_name='textproperties',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.field'),
        ),
    ]
