# Generated by Django 5.0 on 2024-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0002_alter_containerproperty_blur_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textproperties',
            name='line_height',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
