# Generated by Django 5.0 on 2023-12-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0003_remove_field_style_textproperties_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='id',
            new_name='_id',
        ),
    ]
