# Generated by Django 5.0 on 2024-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0003_alter_hackathon_image1_alter_hackathon_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='mode_of_conduct',
            field=models.CharField(max_length=250),
        ),
    ]
