# Generated by Django 5.0 on 2024-05-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0004_alter_hackathon_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='number_of_registeration',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='total_number_rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
