# Generated by Django 5.0 on 2023-12-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0004_rename_id_field__id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='containerproper',
            old_name='id',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='textproperties',
            old_name='id',
            new_name='_id',
        ),
    ]
