# Generated by Django 5.0 on 2023-12-18 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0005_rename_id_container__id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='style',
        ),
        migrations.CreateModel(
            name='Containerproperty',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Color', models.CharField(max_length=200)),
                ('border_color', models.CharField(max_length=200)),
                ('border_width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.container')),
            ],
        ),
        migrations.DeleteModel(
            name='Containerproper',
        ),
    ]
