# Generated by Django 5.0 on 2024-05-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0006_hackathon_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='contact1_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='contact2_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
