# Generated by Django 5.0 on 2023-12-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0006_remove_container_style_containerproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='hackathon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.hackathon'),
        ),
    ]
