# Generated by Django 5.0 on 2024-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0007_alter_hackathon_contact1_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerproperty',
            name='blur_radius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='containerproperty',
            name='border_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='containerproperty',
            name='border_radius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
