# Generated by Django 5.0 on 2023-12-18 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0007_container_hackathon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproperties',
            name='field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.field'),
        ),
    ]
