# Generated by Django 5.0 on 2023-12-18 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0009_alter_containerproperty_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='image1',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image2',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image3',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image4',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='image5',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='logo',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='logo'),
        ),
    ]
