# Generated by Django 5.0 on 2023-12-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0010_alter_hackathon_image1_alter_hackathon_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='website',
            field=models.CharField(max_length=100),
        ),
    ]
