# Generated by Django 5.0 on 2023-12-22 16:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0012_hackathon_organisation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerproperty',
            name='Color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='containerproperty',
            name='container',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.container'),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('container', 'container')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='field',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.field'),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='font',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='font_weight',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=100, message='Value must be greater than or equal to {limit_value}.'), django.core.validators.MaxValueValidator(limit_value=900, message='Value must be less than or equal to {limit_value}.')]),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='italics',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='letter_spacing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='strikethrogh',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='text_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='underline',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textproperties',
            name='upper_case',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
