# Generated by Django 5.0 on 2023-12-22 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon_template', '0013_alter_containerproperty_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproperties',
            name='field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathon_template.field'),
        ),
    ]
