# Generated by Django 5.0 on 2024-04-21 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hackathons_registration', '0002_remove_slider_label_remove_slider_max_value_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant_name', models.CharField(blank=True, max_length=100)),
                ('participant_email', models.EmailField(blank=True, max_length=254)),
                ('participant_phone', models.IntegerField(null=True)),
                ('participant_gender', models.CharField(blank=True, max_length=10)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.hackathonregisterationform')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.members')),
            ],
        ),
        migrations.CreateModel(
            name='Multiplefieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(default={})),
                ('multiple_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.multiplechoicefield')),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='Longfieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
                ('long_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.longanswerfield')),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='LinearfieldSlider',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.IntegerField()),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.slider')),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.FileField(upload_to='file_register')),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='Dropdownfieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(default={})),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='Datefieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('date_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.date')),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='RangefieldSlider',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('min_date', models.IntegerField()),
                ('max_date', models.IntegerField()),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.slider')),
            ],
        ),
        migrations.CreateModel(
            name='Shortfieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=500)),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
                ('short_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.shortanswerfield')),
            ],
        ),
        migrations.CreateModel(
            name='Sliderfieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.slider')),
            ],
        ),
        migrations.CreateModel(
            name='Stepperfieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
            ],
        ),
        migrations.CreateModel(
            name='Tagfield',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(default={})),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
                ('tags_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Togglefieldinput',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('input', models.BooleanField()),
                ('registeration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_participation.participation')),
                ('toggle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.toggle')),
            ],
        ),
    ]
