# Generated by Django 5.0 on 2024-05-21 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0001_initial'),
        ('user_participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dropdownfieldinput',
            name='dropdown_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.dropdownfield'),
        ),
    ]
