# Generated by Django 5.0 on 2024-04-21 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0005_stepper_label'),
        ('user_participation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepperfieldinput',
            name='stepper_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.stepper'),
        ),
    ]
