# Generated by Django 5.0 on 2024-04-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons_registration', '0007_slider_label'),
        ('user_participation', '0002_stepperfieldinput_stepper_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='file_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hackathons_registration.fileupload'),
        ),
    ]
