# Generated by Django 5.0 on 2024-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_participation', '0003_fileupload_file_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datefieldinput',
            old_name='date',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='dropdownfieldinput',
            old_name='options',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='fileupload',
            old_name='answer',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='linearfieldslider',
            old_name='answer',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='longfieldinput',
            old_name='text',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='multiplefieldinput',
            old_name='options',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='rangefieldslider',
            old_name='max_date',
            new_name='input1',
        ),
        migrations.RenameField(
            model_name='rangefieldslider',
            old_name='min_date',
            new_name='input2',
        ),
        migrations.RenameField(
            model_name='shortfieldinput',
            old_name='text',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='sliderfieldinput',
            old_name='value',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='stepperfieldinput',
            old_name='value',
            new_name='input',
        ),
        migrations.RenameField(
            model_name='tagfield',
            old_name='options',
            new_name='input',
        ),
    ]
