# Generated by Django 5.0 on 2024-05-14 18:27

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('otp', models.CharField(max_length=128)),
                ('salt', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiration_minutes', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, choices=[('student', 'student'), ('professional', 'professional')], default=' ', max_length=500, null=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(default=' ', max_length=250)),
                ('gender', models.CharField(default=' ', max_length=250)),
                ('city', models.CharField(default=' ', max_length=250)),
                ('organisation', models.CharField(default=' ', max_length=250)),
                ('cousrse_name', models.CharField(default=' ', max_length=250)),
                ('course_end_year', models.IntegerField(default=-1)),
                ('date_of_birth', models.DateField(null=True)),
                ('interest', models.JSONField(default={})),
                ('about', models.CharField(default=' ', max_length=3000)),
                ('education_qualification', models.CharField(default=' ', max_length=100)),
                ('specialization', models.CharField(default=' ', max_length=200)),
                ('percentage', models.IntegerField(default=-1)),
                ('degree', models.CharField(default=' ', max_length=200)),
                ('facebook', models.CharField(default=' ', max_length=100)),
                ('x', models.CharField(default=' ', max_length=50)),
                ('instagram', models.CharField(default=' ', max_length=100)),
                ('linkedin', models.CharField(default=' ', max_length=100)),
                ('github', models.CharField(default=' ', max_length=100)),
                ('medium', models.CharField(default=' ', max_length=100)),
                ('reddit', models.CharField(default=' ', max_length=100)),
                ('slack', models.CharField(default=' ', max_length=100)),
                ('dribble', models.CharField(default=' ', max_length=100)),
                ('behance', models.CharField(default=' ', max_length=100)),
                ('codepen', models.CharField(default=' ', max_length=100)),
                ('figma', models.CharField(default=' ', max_length=100)),
                ('phone', models.CharField(default=' ', max_length=10, null=True)),
                ('skill', models.ManyToManyField(blank=True, default=None, to='user.skill')),
            ],
        ),
    ]
