# Generated by Django 5.0 on 2024-04-01 16:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('organisation', models.CharField(max_length=250)),
                ('cousrse_name', models.CharField(max_length=250)),
                ('course_duration', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('interest', models.CharField(max_length=250)),
                ('about', models.CharField(max_length=3000)),
                ('education_qualification', models.CharField(max_length=100)),
                ('degree_type', models.CharField(max_length=300)),
                ('specialization', models.CharField(max_length=200)),
                ('degree_duration', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('university_name', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=100)),
                ('x', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('reddit', models.CharField(max_length=100)),
                ('slack', models.CharField(max_length=100)),
                ('dribble', models.CharField(max_length=100)),
                ('behance', models.CharField(max_length=100)),
                ('codepen', models.CharField(max_length=100)),
                ('figma', models.CharField(max_length=100)),
                ('skill', models.ManyToManyField(default=None, to='user.skill')),
            ],
        ),
    ]
