# Generated by Django 5.0 on 2024-05-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, default=None, to='user.skill'),
        ),
    ]
